package main

import (
	"bytes"
	"os"
	"strings"

	charmlog "charm.land/log/v2"

	"github.com/evanmschultz/laslig"
)

// main renders one demo showing charm/log output captured into a Läslig log block.
func main() {
	var transcript bytes.Buffer

	logger := charmlog.NewWithOptions(&transcript, charmlog.Options{
		Formatter:       charmlog.TextFormatter,
		ReportTimestamp: false,
	})

	logger.Info("boot complete", "component", "cache")
	logger.Warn("retry scheduled", "after", "3s")
	logger.Error("dependency missing", "name", "git")

	printer := laslig.New(os.Stdout, laslig.Policy{
		Format: laslig.FormatAuto,
		Style:  laslig.StyleAuto,
	})

	_ = printer.Section("Logging")
	_ = printer.Paragraph(laslig.Paragraph{
		Title:  "charm/log transcript",
		Body:   "This example uses charm.land/log/v2 as the logger and hands the captured output to Läslig for presentation.",
		Footer: "Logging stays caller-owned. Läslig only renders the transcript block.",
	})
	_ = printer.LogBlock(laslig.LogBlock{
		Title:  "captured log output",
		Body:   strings.TrimRight(transcript.String(), "\n"),
		Footer: "Generated by charm/log and rendered by Läslig.",
	})
}
